name: 01 - Variables

on:
  workflow_dispatch

env:
  VARIABLE1 : 'value1'
  
jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Print variable
        run: echo "VARIABLE1 = " ${{ env.VARIABLE1 }}

