name: Accessing contexts
on: 
  workflow_dispatch

jobs:
  ShowContexts:
    runs-on: ubuntu-latest
    
    steps:
      - name: Some github properties
        run: |
          echo '${{ github.triggering_actor }}'
          echo '${{ github.event.repository.default_branch }}'
          echo '${{ github.sender.id }}'
          
      - name: Some runner properties
        run: |
          echo '${{ runner['os'] }}'
          echo '${{ runner['workspace'] }}'
          echo '${{ runner.name }}'
