name: Action Parameters

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 
      print_tags:
        description: 'True to print to STDOUT'
        required: true 
        type: boolean
      tags:
        description: 'Test scenario tags'
        required: false 
        type: string
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true 
  
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Echo inputs
        run: echo '${{ toJSON(inputs) }}'
  
  
