name: Matrix (exclude)

on: 
  workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: ['northeurope','westeurope']
        environment: ['dev','test']
        slot: ['blue','green']
    steps:
      - run: echo 'Deploying on region ${{ matrix.region}} environment ${{ matrix.environment}} with ${{ matrix.slot }}'
      - run: date
      - run: sleep 5 
      - run: date
