name: Matrix

on: 
  workflow_dispatch

jobs:
  job1:
    runs-on: ${{ matrix.os}}
    strategy:
      matrix:
        version: [10, 12, 14]
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Print os-version
        run: echo '${{ matrix.os}} - ${{ matrix.version}}'
