name: Matrix (include)

on: 
  workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: ['northeurope','westeurope']
        environment: ['dev','test']
        slot: ['blue','green']
        include:
          - region: 'northeurope'
            environment: 'preprod'
            slot: 'black'
          - region: 'northeurope'
            environment: 'preprod'
            slot: 'blue'
          - region: 'eastus'
            environment: 'preprod'
            slot: 'blue'
    steps:
      - run: echo 'Deploying on region ${{ matrix.region}} environment ${{ matrix.environment}} with ${{ matrix.slot }}'
      - run: date
      - run: sleep 5 
      - run: date
