name: Matrix (simple)

on: 
  workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        region: ['northeurope','westeurope','westus']
        environment: ['dev','test','prod']
    steps:
      - run: echo 'Region=${{ matrix.region}} Env=${{ matrix.environment}}'
      - run: date
      - run: sleep 5 
      - run: date
