name: Matrix (include)

on: 
  workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        region: ['northeurope','westeurope','westus']
        environment: ['dev','test','prod']
        include:
          - environment: 'preprod'
    steps:
      - run: echo 'Deploying on region ${{ matrix.region}} environment ${{ matrix.environment}}'
      - run: date
      - run: sleep 5 
      - run: date
