name: Output variables

on:
  workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Do something
        run: echo "Hello World!!"
    outputs:
      RESULT : "Result from step 'job1'"
  job2:
    runs-on: windows-latest
    steps:
      - name: Print job1 result
        run: echo "VARIABLE1 = " ${{ jobs.job1.output.RESULT }}
