name: Output variables

on:
  workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Do something
        run: echo "Hello World!!"
    outputs:
      RESULT : ResultValue
  job2:
    runs-on: windows-latest
    needs: [job1]
    steps:
      - name: Print job1 result
        run: echo "RESULT = " ${{ needs.job1.outputs.RESULT }}
