name: Reusable workflow

on:
  workflow_call:
    inputs:
      plainInput:
        required: true
        type: string
        description: 'This is a plain value'
    secrets:
      secretInput:
        required: true
        description: 'This is a secret'
        
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print plainInput
        run: echo "plainInput = " ${{ inputs.plainInput }}
      - name: Print secretInput
        run: echo "secretInput = " ${{ secrets.secretInput }}
