name: Caller workflow

on:
  workflow_dispatch
  
jobs:
  call-workflow1:
    uses: ./.github/workflows/Reusable_Workflow.yml
    with:
      input1: 'Hello'
      input2: 'World'
      
  write_workflow_out1:
    runs-on: ubuntu-latest
    needs: call-workflow1
    steps:
      - run: echo ${{ needs.call-workflow1.outputs.outValue }}
      
  call-workflow2:
    uses: massimobonanni/variablesInActions/.github/workflows/Reusable_Workflow.yml@a9d321d5e4dceb62d401e95cefed16109377d122
    with:
      input1: 'Hi'
      input2: 'Mars'
      
  write_workflow_out12:
    runs-on: ubuntu-latest
    needs: call-workflow2
    steps:
      - run: echo ${{ needs.call-workflow2.outputs.outValue }}
