name: Caller workflow

on:
  workflow_dispatch
  
jobs:
  call-workflow1:
    uses: ./.github/workflows/Reusable_Workflow.yml
    with:
      plainInput: 'call1'
    secrets:
      secretInput: 'secret1'
