name: Script Injection

on:
  issues:
    types:
      - opened
      
jobs:
  dangerous_job:
    runs-on: ubuntu-latest
    steps:
      - name: Show title
        run: |
          title="${{ github.event.issue.title}}"
          echo $title
          if [[ $title =~ ^MAX ]]; then
            echo "Title starts with MAX"
            exit 0
          else
            echo "Title doesn't start with MAX"
            exit 1
          fi
