name: Script Injection

on:
  issues:
    types:
      - opened
      
jobs:
  dangerous_job:
    runs-on: ubuntu-latest
    steps:
      - name: Show title
        run: |
          title="${{ github.event.issue.title}}"
          echo "Issue with title"
