name: Secrets
on: 
  workflow_dispatch

jobs:
  ShowContexts:
    runs-on: ubuntu-latest
    
    steps:
      - name: Show simple secret
        run: echo '${{ secrets.SIMPLE_SECRET }}'
      - name: Some JSON secret
        run: echo '${{ secrets.JSON_SECRET }}'
