name: Secrets (environments)
on: 
  workflow_dispatch

jobs:
  ShowContexts:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ['prod','preprod','test']
    environment: ${{ matrix.environment }}
    steps:
      - name: Show environment secret
        run: echo '${{ secrets.MYSECRET }}'
