name: Secrets (environments)
on: 
  workflow_dispatch

jobs:
  ShowContexts:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ['prod','preprod','test']
    environment: ${{ matrix.environment }}
    steps:
      - name: Show environment secret (reverse)
        env:
            SECRET : secrets.MYSECRET
        run: |
          strlen='${{ env.SECRET }}'
          for (( i=$strlen-1; i>=0; i-- ));
          do
            revstr=$revstr${s:$i:1}
          done
          echo "Reversed secret : $revstr"
