name: Secrets (environments)
on: 
  workflow_dispatch

jobs:
  ShowContexts:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ['prod','preprod','test']
    environment: ${{ matrix.environment }}
    steps:
      - name: Show environment secret (reverse)
        run: |
          s='${{ secrets.MYSECRET }}'
          strlen=${#s}
          for (( i=0; i<=$strlen-1; i++ ));
          do
            secretStr=$secretStr${s:$i:1}
          done
          echo "Secret : $secretStr"
