name: Variables Scopes

on:
  workflow_dispatch

env:
  VARIABLE1 : 'Workflow'
  
jobs:
  workflowValue:
    runs-on: ubuntu-latest
    env:
      VARIABLE1 : "job"
    steps:
      - name: Print Hello World
        env:
            VARIABLE1 : "step"
        run: echo "Hello World
        
      - name: Print Hello World...Again
        run: echo "Hello World
  
