name: Variables Scopes

on:
  workflow_dispatch

env:
  VARIABLE1 : 'Workflow'
  
jobs:
  workflowValue:
    runs-on: ubuntu-latest
    steps:
      - name: Print variable
        run: echo "VARIABLE1 = " ${{ env.VARIABLE1 }}
        
  jobValue:
    runs-on: ubuntu-latest
    env:
      VARIABLE1 : "job"
    steps:
      - name: Print variable
        run: echo "VARIABLE1 = " ${{ env.VARIABLE1 }}
      - name: Print variable
        run: echo "VARIABLE1 = " ${{ jobs.jobValue.env.VARIABLE1 }}
        
  stepValue:
    runs-on: ubuntu-latest
    steps:
      - name: Print variable
        id: printVariable
        env:
            VARIABLE1 : "StepValue - Step 'Print variable'"
        run: |
          echo "VARIABLE1 = " ${{ env.VARIABLE1 }}
          echo "VARIABLE1 = " ${{ jobs.stepValue.env.VARIABLE1 }}
          echo "VARIABLE1 = " ${{ jobs.stepValue.printVariable.env.VARIABLE1 }}
