name: Variables Scopes

on:
  workflow_dispatch

env:
  VARIABLE1 : 'Workflow'
  
jobs:
  workflowValue:
    runs-on: ubuntu-latest
    steps:
      - name: Print variable
        run: echo "VARIABLE1 = " ${{ env.VARIABLE1 }}
        
  jobValue:
    runs-on: ubuntu-latest
    env:
      VARIABLE1 : "job"
    steps:
      - name: Print variable
        run: echo "VARIABLE1 = " ${{ env.VARIABLE1 }}
        
  stepValue:
    runs-on: ubuntu-latest
    steps:
      - name: Print variable
        id: stepValue
        env:
            VARIABLE1 : "StepValue - Step 'Print variable'"
        run: echo "VARIABLE1 = " ${{ env.VARIABLE1 }}
        
  references:
    runs-on: ubuntu-latest
    needs: [jobValue,stepValue]
    steps:
      - name: Print workflow value
        run: echo "VARIABLE1 = " ${{ env.VARIABLE1 }}
      - name: Print job value
        run: echo "VARIABLE1 = " ${{ job.stepValue.env.VARIABLE1 }}
      - name: Print step value
        run: echo "VARIABLE1 = " ${{ job.stepValue.steps['stepValue'].env.VARIABLE1 }}
